name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write    # potrzebne do tworzenia release
  packages: write
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set version
      id: version
      run: T=$(date +%s) ; echo -e "TIME=$T\nRELEASE_TAG=v1.0.$T" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
          sudo apt install -y build-essential cmake pkg-config qt5-qmake qtbase5-dev
    - name: diskUsageMonitor.deb
      run: make diskUsageMonitor.deb time=${{ env.TIME }}
    - name: Create GitHub Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.RELEASE_TAG }}
        name: ${{ env.RELEASE_TAG }}
        body: "Release of diskUsageMonitor.deb package"
    - name: Upload diskUsageMonitor.deb to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  # <--- tutaj
        asset_path: ./diskUsageMonitor.deb
        asset_name: diskUsageMonitor.deb
        asset_content_type: application/vnd.debian.binary-package
